### ISSUE TITLE
No Devices Shown

### ISSUE THREAD

**Issue by xd20111** [XploitWizer/XploitSPY#28]
I installed app but now showing deshbord

**Comment by RaoMK** [comment]
@xd20111 please explain it a bit in detail which device are you using and on which server you setup it 
because we test it upto android 10 and its working fine.
Make sure you are using latest codes and following latest commands given in readme.md file 
also make sure that if you are using it on localhost we don't recommend it, because then it will work only on same network and you also need to put your IP while building apk

**Comment by somesh2611** [comment]
Device not found after 1/2 HR plz tell me how to fix

**Comment by ryuk-dev** [comment]
Open the website in desktop mode

**Comment by RaoMK** [comment]
@somesh2611 if you are using Heroku free version then it auto reset the whole codes it's limitation of heroku free version

**Comment by chrisstone07** [comment]
Closing as no response from user.

**Comment by xd20111** [comment]
> 
> 
> @xd20111 please explain it a bit in detail which device are you using and on which server you setup it
> because we test it upto android 10 and its working fine.
> Make sure you are using latest codes and following latest commands given in readme.md file
> also make sure that if you are using it on localhost we don't recommend it, because then it will work only on same network and you also need to put your IP while building apk

sir im using AWS kali Linux rdp here panel link 3.21.94.26 and I tried  with nokia 6 , Pixel 3, note 9
